FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy entire project
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o microservice-b ./microservice-b/cmd/b

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/microservice-b .
COPY --from=builder /app/microservice-b/internal/db ./internal/db

EXPOSE 8080 9090

CMD ["./microservice-b"]