basePath: /
definitions:
  domain.PaginatedSensorReadings:
    properties:
      data:
        description: Array of sensor readings
        items:
          $ref: '#/definitions/domain.SensorReading'
        type: array
      page:
        description: Current page number
        example: 1
        type: integer
      page_size:
        description: Items per page
        example: 10
        type: integer
      total_items:
        description: Total number of items
        example: 100
        type: integer
      total_pages:
        description: Total number of pages
        example: 10
        type: integer
    type: object
  domain.SensorReading:
    properties:
      id:
        description: Unique identifier
        example: 1
        type: integer
      id1:
        description: First identifier (A-Z)
        example: A
        type: string
      id2:
        description: Second identifier (0-999)
        example: 42
        maximum: 999
        minimum: 0
        type: integer
      sensor_type:
        description: Type of sensor
        example: temperature
        type: string
      timestamp:
        description: When reading was taken
        example: "2024-01-15T10:30:00Z"
        type: string
      value:
        description: Sensor reading value
        example: 23.5
        type: number
    required:
    - id1
    - id2
    - sensor_type
    - value
    type: object
  handler.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.LoginResponse:
    properties:
      token:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: joydeeppaul9000@gmail.com
    name: API Support
  description: API for managing sensor data readings with microservice architecture
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Synthetic Sensors API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Invalid request format
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - Authentication
  /api/readings:
    delete:
      consumes:
      - application/json
      description: Delete sensor readings based on filter criteria (requires admin
        privileges)
      parameters:
      - description: Filter by ID1 (A-Z)
        in: query
        name: id1
        type: string
      - description: Filter by ID2 (0-999)
        in: query
        name: id2
        type: integer
      - description: Start timestamp (RFC3339 format)
        in: query
        name: from
        type: string
      - description: End timestamp (RFC3339 format)
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Readings deleted successfully with count
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden - Admin access required
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Delete sensor readings
      tags:
      - Sensor Readings
    get:
      consumes:
      - application/json
      description: Get sensor readings with optional filtering by ID1, ID2, time range,
        and pagination
      parameters:
      - description: Filter by ID1 (A-Z)
        in: query
        name: id1
        type: string
      - description: Filter by ID2 (0-999)
        in: query
        name: id2
        type: integer
      - description: Start timestamp (RFC3339 format)
        in: query
        name: from
        type: string
      - description: End timestamp (RFC3339 format)
        in: query
        name: to
        type: string
      - description: 'Page number (default: 1)'
        in: query
        name: page
        type: integer
      - description: 'Items per page (default: 10, max: 100)'
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved readings
          schema:
            $ref: '#/definitions/domain.PaginatedSensorReadings'
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get sensor readings
      tags:
      - Sensor Readings
    post:
      consumes:
      - application/json
      description: Create a new sensor reading (requires admin privileges)
      parameters:
      - description: Sensor reading data
        in: body
        name: reading
        required: true
        schema:
          $ref: '#/definitions/domain.SensorReading'
      produces:
      - application/json
      responses:
        "201":
          description: Reading created successfully
          schema:
            $ref: '#/definitions/domain.SensorReading'
        "400":
          description: Invalid request body or validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden - Admin access required
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Create sensor reading
      tags:
      - Sensor Readings
  /api/readings/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific sensor reading by its ID
      parameters:
      - description: Reading ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved reading
          schema:
            $ref: '#/definitions/domain.SensorReading'
        "400":
          description: Invalid ID format
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Reading not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Get sensor reading by ID
      tags:
      - Sensor Readings
    put:
      consumes:
      - application/json
      description: Update an existing sensor reading by ID (requires admin privileges)
      parameters:
      - description: Reading ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated sensor reading data
        in: body
        name: reading
        required: true
        schema:
          $ref: '#/definitions/domain.SensorReading'
      produces:
      - application/json
      responses:
        "200":
          description: Reading updated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid ID format or request body
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden - Admin access required
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Reading not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: Update sensor reading
      tags:
      - Sensor Readings
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
